<?php
// Configuration
$directory = '/home/alutotra/domains/betall.it.com/public_html'; // Update to your directory path
$file_permissions = 0644; // Permissions for files (rw-r--r--)
$folder_permissions = 0755; // Permissions for folders (rwxr-xr-x)
$log_file = 'permissions_log.txt'; // Log file to track changes

// Initialize log
$log = "Permissions Change Log - " . date('Y-m-d H:i:s') . "\n";
$log .= "Setting files to " . decoct($file_permissions) . " and folders to " . decoct($folder_permissions) . "\n\n";

// Function to process files and folders recursively
function change_permissions($directory, $file_permissions, $folder_permissions, &$log) {
    try {
            $iterator = new RecursiveIteratorIterator(
                        new RecursiveDirectoryIterator($directory, RecursiveDirectoryIterator::SKIP_DOTS),
                                    RecursiveIteratorIterator::SELF_FIRST
                                            );

                                                    $files_changed = 0;
                                                            $folders_changed = 0;
                                                                    $skipped = 0;

                                                                            foreach ($iterator as $item) {
                                                                                        $path = $item->getPathname();
                                                                                                    $is_dir = $item->isDir();
                                                                                                                $target_permissions = $is_dir ? $folder_permissions : $file_permissions;

                                                                                                                            // Get current permissions
                                                                                                                                        $current_permissions = fileperms($path) & 0777; // Mask to get only permission bits
                                                                                                                                                    $current_permissions_str = sprintf("%o", $current_permissions);

                                                                                                                                                                // Check if permissions need changing
                                                                                                                                                                            if ($current_permissions !== $target_permissions) {
                                                                                                                                                                                            // Attempt to change permissions
                                                                                                                                                                                                            if (@chmod($path, $target_permissions)) {
                                                                                                                                                                                                                                $log .= ($is_dir ? "Folder" : "File") . " permissions changed: $path ($current_permissions_str -> " . decoct($target_permissions) . ")\n";
                                                                                                                                                                                                                                                    if ($is_dir) {
                                                                                                                                                                                                                                                                            $folders_changed++;
                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                        $files_changed++;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                $log .= "Skipped (failed to change permissions): $path\n";
                                                                                                                                                                                                                                                                                                                                                                                                    $skipped++;
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                $log .= "Skipped (already correct): $path ($current_permissions_str)\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $log .= "\nSummary: $files_changed files changed, $folders_changed folders changed, $skipped items skipped.\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $log .= "Error: " . $e->getMessage() . "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return $log;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Execute the permissions change
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $log .= change_permissions($directory, $file_permissions, $folder_permissions, $log);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Save log to file
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                file_put_contents($log_file, $log);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Output results to browser
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo nl2br(htmlspecialchars($log));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>